spring:
  application:
    name: hashi

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liGJd6oGPfPKXKRJ
            client-secret: 9dcfa625e287f4937317e310fbe30b4cde70f5de
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id


  datasource:
    url: jdbc:mysql://localhost:3306/coupang
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012